= Cache

`Xtuple\Util\Cache` package provides interfaces and classes to work cache data.
Interface `Xtuple\Util\Cache\Cache` should be used to implement cache itself.
Each cache is a set of records `Xtuple\Util\Cache\Record\Record` that are stored
and identified by their key `Xtuple\Util\Cache\Key\Key`.
`Key` and `Record` are generic types,
and concrete implementations may extend them to provide more details.
For example, implementation for an SQL database may use key as a string, stored in a column,
or as a compound key, stored in multiple columns.
In each case an extending interfaces and classes may specify this behavior.

`Xtuple\Util\Cache\Cache` extends `\Serializable` interface.
Caches are required to handle serialization correctly,
without creation of duplicate set of data.

`Xtuple\Util\Cache\Cache\Memory\MemoryCache` is a basic implementation of a cache
that can be used to cache information during a request or for testing purposes.
`MemoryCache` uses `static` variables to store data and is not persistent.

.Using `MemoryCache`
[source,php]
----
include::./cache.example.php[lines=6..-1]
----
