= Collection

`Xtuple\Util\Collection` package provides classes to work with collections of elements.
It contains abstract and default implementations for both strictly typed and untyped data.
All collections are iterable and countable.

[NOTE]
PHP doesn't allow to use the word `List` as a namespace or a class name,
so the term `Sequence` is used instead for the namespace and root interface.
All the classes are named using the term `List`.

[NOTE]
PHP doesn't have a default mechanism for object identity,
so the `Set` is defined not by elements' identity,
but by their key method (similarly to `Map`).

Default implementation class path for any collection type follows the same pattern:
`{Abstract Data Type}/{Implementation type}/{Narrowing customization}`
(e.g. `Xtuple\Util\Collection\Map\ArrayMap\StrictType\StrictlyTypedArrayMap`).

Strict type abstract collections should be used to have generic collections.
Original collection type interfaces should be extended to provide type information in PHPDocs.

Example: defining class to provide `ArrayList<stdClass>` list.

[source]
.ListStdClass.php - interface definition
----
include::./collection1.example.php[lines=5..-1]
----
<1> Optional hint in "generic" notation.
May be useful for long and complicated data structures.
<2> Extending original list interface `Sequence`.
<3> Overriding `get()` definition, to specify `@return \stdClass|null` instead of `@return mixed|null`.
<4> Overriding `current()` definition, to specify return type.
`Sequence::key()` doesn't need to be overridden, as its types are the same for all lists.
<5> Additional methods can be added to this type.

[NOTE]
`@generic` PHPDoc tag is used to mark interface methods that need to be overridden with more specific types.

[source]
.ArrayListStdClass.php - actual class implementation
----
include::./collection2.example.php[lines=5..-1]
----
<1> `AbstractStrictlyTypedArrayList` automatically checks elements' types.
<2> Specify implemented interface to reference overridden `get()` and `current()` methods.
<3> Overriding constructor PHPDoc to narrow type hint
(`@param \stdClass[] $elements` instead of `@param array $elements`)
and hide `$type` parameter
<4> Pass exact type `stdClass` into parent constructor.
<5> Implementation of the additional method defined in `ListStdClass`.

include::collection/list.adoc[leveloffset=+1]
include::collection/map.adoc[leveloffset=+1]
include::collection/set.adoc[leveloffset=+1]
include::collection/stack.adoc[leveloffset=+1]
include::collection/tree.adoc[leveloffset=+1]
