= Exception

`Xtuple\Util\Exception` package provides a set of classes to throw translatable exceptions.

`Xtuple\Util\Exception\Throwable` is the base interface for all exceptions,
and `Xtuple\Util\Exception\AbstractThrowable` is the base abstract class for all the exceptions.
Unlike other packages,
this package is not using decorators for abstract classes.
Instead, `Xtuple\Util\Exception\AbstractThrowable` extends `\Exception`
to utilize the default implementation of the `\Throwable` interface
(3rd party PHP code usually catches `\Exception`, not `\Throwable`).
All the implementations of `Xtuple\Util\Exception\AbstractThrowable` represent different shortcuts of its constructor.

`Xtuple\Util\Exception\Throwable` provides three methods:

* `message(): \Xtuple\Util\Type\String\Message\Message\Message` - translatable exception message.
* `exceptions(): \Xtuple\Util\Exception\Collection\Sequence\ListThrowable` - list of all previous exceptions,
starting with the original exception.
* `errors(): \Xtuple\Util\Type\String\Message\Message\Collection\Sequence\ListMessage` - list of error messages,
collection for the exception.
This allows to throw one "final" exception for all occurred issues
(e.g. all errors from multiple async HTTP requests).

`Xtuple\Util\Exception\AbstractThrowable` provides final implementations for all these methods,
and also overrides the default `__toString()`,
to return information about all previous exceptions
and all error messages inside them,
instead of the stack trace for the exception.

include::exception/exception.adoc[leveloffset=+1]
include::exception/chain-exception.adoc[leveloffset=+1]
include::exception/multi-error-exception.adoc[leveloffset=+1]
