= Measure

`Xtuple\Util\Type\Measure` package handles units of measurement.

`Xtuple\Util\Type\Measure\Unit` is a base interface for a UOM.
Each unit must provide a symbol, name, list of synonyms
and methods to convert to and from SI unit.
Each measurement (e.g. `LengthUnit`) extends `Unit` it to provide additional methods.

== Length

`Xtuple\Util\Type\Measure\Length\Length` interface is used to handle measurement in length (distance) units
(`Xtuple\Util\Type\Measure\Length\Unit\LengthUnit`).
`Xtuple\Util\Type\Measure\Length\Unit\Unit\Meter` is a base (SI) unit for length.

`Xtuple\Util\Type\Measure\Length\Unit\Collection\Set\LengthUnits` is a `Set<LengthUnit>`
that contains all supported units.
`Set<LengthUnit>` is using `LengthUnit::symbol()` as a key.
`Xtuple\Util\Type\Measure\Length\Unit\Collection\Set\ArraySetLengthUnit` allow to create any custom set of units
with a custom key value.
`Set<LengthUnit>` has `find(string $search): LengthUnit` to try find a unit across all synonyms.

.Using `Xtuple\Util\Type\Measure\Length` package
[source]
----
include::./measure.length.example.php[lines=5..-1]
----

== Mass

`Xtuple\Util\Type\Measure\Mass\Mass` interface is used to handle measurement in mass (weight) units
(`Xtuple\Util\Type\Measure\Mass\Unit\MassUnit`).
`Xtuple\Util\Type\Measure\Mass\Unit\Unit\Kilogram` is a base (SI) unit for length.

`Xtuple\Util\Type\Measure\Mass\Unit\Collection\Set\MassUnits` is a `Set<MassUnit>` that contains all supported units.
`Set<MassUnit>` is using `MassUnit::symbol()` as a key.
`Xtuple\Util\Type\Measure\Mass\Unit\Collection\Set\ArraySetMassUnit` allow to create any custom set of units
with a custom key value.
`Set<MassUnit>` has `find(string $search): MassUnit` to try find a unit across all synonyms.

.Using `Xtuple\Util\Type\Measure\Mass` package
[source]
----
include::./measure.mass.example.php[lines=5..-1]
----
