= Message (Localizable string)

`Xtuple\Util\Type\String\Chars\Message` package provides set of localizable/translatable string classes.
Name `Message` was inspired by the underlying
link:http://php.net/manual/en/book.intl.php[PHP Intl extension] terminology
(see http://php.net/manual/en/class.messageformatter.php[MessageFormatter class]).
PHP `intl` extension wraps up
link:http://site.icu-project.org[ICU - International Components for Unicode] library,
which makes localization handling highly reliable.

[NOTE]
In general, localization and translation are not the same:
a text in the same language may require different output for the numbers or dates inside it for different locales.
But for convenience,
these terms would be used interchangeably in this section of documentation,
as any localizable string in this package is also translatable.

`Xtuple\Util\Type\String\Chars\Message\Message\Message` is the base type (interface)
that defines requirements for a translatable string:

- `Message::__toString()` must return a string, localized for `en_US.UTF-8` locale.
- `Message::format(string $locale): string` returns a string localized for a custom locale.
- `Message::template(): string` returns a template used for a string.
Interpolation delimiters are not strictly specified,
for compatibility with other frameworks (e.g. Drupal),
but by default curly brackets (`{}`) are used and are strongly recommended to be kept.
- `Message::arguments(): Set<Argument>` returns set of arguments used in the template.
Arguments may contain delimiters for compatibility with other frameworks,
but by default are not used.

`template()` and `arguments()` methods should be used by translation packages to retrieve original data.
Some message subtypes, e.g. `PluralMessage`,
define more methods to access other data forms,
that may be needed for localization.

`Xtuple\Util\Type\String\Chars\Message\Argument` is a `Message` that is used as an argument for other messages:

- `Argument::key()` returns a key - name of the argument inside the message.

.Using `Xtuple\Util\Type\String\Chars\Message\Message`
[source]
----
include::./message.example.php[lines=6..-1]
----

== Types

Various types of messages are present in `Xtuple\Util\Type\String\Message\Type`.
Each subpackage may declare a custom `Message` subtype and provide abstractions for `Message` and `Argument`.
Type subpackages may have even more narrowed down subtypes:
for example,
`Number` type contains `Currency` subtype,
along with other number-related subtypes.

String (`Xtuple\Util\Type\String\Message\Type\String`) is the most basic one,
used just to fulfill the strict type requirements of `Set<Argument>` and `Set<Message>`.
Example of its usage is provided in the section above.

Examples below provided only for `Message` types,
but they can also be used with corresponding `Argument` types.

[NOTE]
`Xtuple\Util\Type\String\Message\Type\DateTime\DateTimeMessage`
default implementation currently do not use `php-intl` package,
due to the difference between commonly used `date()` formatting options and `\IntlDateFormatter`.
This also renders `Message::format($locale)` method redundant,
as its parameter doesn't change the output.
`DateTimeMessage::timezone(?string $timezone = null)`
should be used to render date for the given format in the specified timezone.

.Using `Xtuple\Util\Type\String\Message\Type\DateTime\DateTimeMessage`
[source]
----
include::./message.types1.example.php[lines=5..-1]
----

.Using `Xtuple\Util\Type\String\Message\Type\Number\NumberMessage`
[source]
----
include::./message.types2.example.php[lines=5..-1]
----

`Xtuple\Util\Type\String\Message\Type\Plural\PluralMessage`
adds methods for `Message` required for correct translation of a text with a plural value.

- `PluralMessage::count(): NumberMessage` - count value is localizable too.
- `PluralMessage::singular(): ?Message` - singular translation is optional
(this would depend on the language).
- `PluralMessage::plural(): Message` - is the default value and a fallback message.
- `PluralMessage::plurals(): Set<Argument>` - additional
link:http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html[plural forms]
may be provided,
including exact values (`=0`, `=1`, etc.)
- `PluralMessage::offset(): ?float` - optional offset for the count value.
Usually useful when exact value plurals provided.

.Using `Xtuple\Util\Type\String\Message\Type\Plural`
[source]
----
include::./message.types3.example.php[lines=5..-1]
----

`Xtuple\Util\Type\String\Message\Type\Select\SelectMessage`
adds methods for `Message` required for correct translation of messages with custom selection rules.
The basic example would be a selection of correct pronoun based on user's gender.

- `SelectMessage::value(): string` - actual value, select "option"
- `SelectMessage::default(): Message` - default message, a fallback variant.
- `SelectMessage::options(): Set<Argument>` - messages to select from.

.Using `Xtuple\Util\Type\String\Message\Type\Select`
[source]
----
include::./message.types4.example.php[lines=5..-1]
----
