= String

`Xtuple\Util\Type\String\Chars` interface describes default string data.
It contains only `__toString(): string` method, as any string data must be easily casted to `string`.

== Encoding

`Xtuple\Util\Type\String\Encoding` package contains sub-packages to support various string encodings.

`Xtuple\Util\Type\String\Encoding\Base64` is used to represent binary data in ASCII format.

`Xtuple\Util\Type\String\Encoding\Base64\Encode\URLSafe` can be used to encode data
that must be safe to pass in the URL.
URL safe base64 encoding replaces `+` and `/` characters with `-` and `_`.

`Xtuple\Util\Type\String\Encoding\Base64\Encode\URLSafe\JSON` is a shortcut,
to additionally do JSON transformation of the data, before encoding it to base64.

.Using `Xtuple\Util\Type\String\Encoding\Base64` package
[source]
----
include::./string.encoding.base64.example.php[lines=5..-1]
----

.Using `Xtuple\Util\Type\String\Encoding\HTML` package
[source]
----
include::./string.encoding.html.example.php[lines=5..-1]
----

== Transliteration

`Xtuple\Util\Type\String\Transliteration` package provides a basic classes
to transform input in non-latin characters to latin.
link:http://php.net/manual/en/book.intl.php[PHP Intl extension] is used to perform transliteration.

`Xtuple\Util\Type\String\Transliteration\Slug` allows to prepare user input to be used in URLs.

.Using `Xtuple\Util\Type\String\Transliteration`
[source]
----
include::./string.transliteration.example.php[lines=6..-1]
----
