= Code style

link:https://www.jetbrains.com/help/phpstorm/settings-code-style.html[Code-style settings]
are located in `Preferences → Editor → Code-Style`.
Current file or all files in the selected directory can be
link:https://www.jetbrains.com/help/phpstorm/using-code-editor.html#reformat_rearrange_code[reformatted]
using `Code → Reformat Code` or `Code → Show Reformat Code Dialog` menus.

Code style has evolved from
link:https://www.drupal.org/docs/develop/standards/coding-standards[Drupal coding standards],
absorbing ideas from
link:https://www.php-fig.org/psr/psr-1/[PSR-1]/
link:https://www.php-fig.org/psr/psr-2/[PSR-2]
and with regard to upcoming PHP language
link:https://wiki.php.net/rfc[features].
The goals of the code style are:

* readability of the code;
* consistency of the code style;
* minimization of the diff/patch output.

== Files

* Files _must_ use only UTF-8 without BOM.
* Files _must_ either declare symbols (classes, functions, constants, etc.)
or cause side-effects
(e.g. generate output, change .ini settings, etc.)
but _must not_ do both.
** The phrase “side effects” means execution of logic
not directly related to declaring classes, functions, constants, etc.,
_merely from including the file_.
* Files _must_ be formatted with `\n` as the line ending (Unix line endings),
not `\r\n` (Windows line endings).
* All text files _must_ end in a single newline (`\n`).
This avoids the verbose "No newline at end of file" patch warning
and makes patches easier to read
since it's clearer what is being changed when lines are added to the end of a file.
* Files _must_ use only full PHP tags `<?php ?>`,
not shorthand `<? ?>`.
* Code _must not_ produce any warnings
when PHP error reporting level is set to `E_ALL`.

=== Line length and wrapping

* All lines of code _should not_ be longer than `120` characters.
* The soft limit on line length _must_ be `120` characters.
** Automated style checkers _must_ warn but _must not_ error at the soft limit.
** Lines containing longer function names, function/class definitions, variable declarations, etc
are allowed to exceed `120` characters.
* Lines _should not_ be longer than `80` characters:
** Lines longer than that _should_ be split into multiple subsequent lines of no more than `80` characters each.
* Single conditions _should not_ be wrapped into multiple lines.
** Multiple conditions _should be_ wrapped into multiple lines.
* Blank lines _must not_ be added to indicate related blocks of code.
* There _must not_ be more than one statement per line.
* Semicolons at the end of code blocks _must_ always be used,
even when PHP allow them to be omitted.
* `example.com` _must_ be used for all example URLs, per
link:https://tools.ietf.org/html/rfc2606[RFC 2606].
* Comment standards are discussed separately.

=== Indenting and Whitespace

* Code _must_ be indented by 2 spaces, with no tabs.
** Code inside PHP tags _must not_ be indented.
* Lines _must not_ have trailing whitespace at the end.

=== Braces

* Opening braces _must_ go on the same line.
* Closing braces _must_ go on the next line after the body.

=== File structure

The header of a PHP file may consist of a number of different blocks.
If present,
each of the blocks below _must_ be separated by a single blank line,
and _must not_ contain a blank line.
Each block _must_ be in the order listed below,
although blocks that are not relevant may be omitted.

* PHP file _must_ start with the `<?php declare(strict_types=1);` line followed by a blank line.
* Opening `<?php declare(strict_type=1);` statement.
* File-level docblock.
* One or more remaining `declare` statements.
* The namespace declaration of the file.
* One or more class-based `use` import statements.
* One or more function-based `use` import statements.
* One or more constant-based `use` import statements.
* The remainder of the code in the file.
* Closing PHP tag `?>` _must_ be omitted in all files.

=== Including Code

* `require_once` _must_ be used for an unconditionally included file.
* `include_once` _must_ be used for a conditionally included file.
* `require` and `include` statements _must not_ be used.
* Parentheses _must not_ be used with `require_once` or `include_once` statements.
* File path _must_ start with `.`, when an included file is located in the same directory or a sub-directory.

=== Keywords

* PHP link:http://php.net/manual/en/reserved.keywords.php[keywords]
and link:http://php.net/manual/en/reserved.keywords.php[reserved] *must* be lowercase,
including predefined constants `true`, `false`, `null`.
* Short form of type keywords _must_ be used i.e. `bool` instead of `boolean`, `int` instead of `integer` etc.
* Pre-defined PHP constants (`true`, `false`, `null`) _must_ be lowercase
(for consistency with all other PHP keywords).

== Operators

* All binary operators (operators that come between two values),
such as `+`, `-`, `=`, `!=`, `==`, `>`, etc. _must_ have a space before and after the operator,
for readability.
* Unary operators (operators that operate on only one value),
such as `++`, _must not_ have a space between the operator and the variable or number they are operating on.
* Checks _must_ use only `!==` operator.
** Weak-typed operands _must_ be explicitly casted.
* The `<>` operator _must not_ be used in PHP code.
* A space _must_ be used between the type and the variable in a cast.
* Ternary operator _must_ be split onto several lines
** The question mark and the colon _must be_ kept at the front of the line.
* The equal signs _must not_ be aligned in block-related assignments.
* Assignments _must_ be split onto several lines when the character/line limit would be exceeded.
** The equal sign has to be positioned onto the following line and indented once.

== Control Structures

* Control structures include `if`, `for`, `while`, `switch`, etc.
* `elseif` _must_ always be used instead of `else if`
(so that all control keywords look like single words).
* `else`, `elseif`, `while` (in `do…while`), `catch` _must_ be on a new line
(so it's in the same column as `if`, `do`, `try` statements).
* The `case` statement _must_ be indented once from `switch`.
* The `break` keyword (or other terminating keyword) _must_ be indented at the same level as the `case` body.
* There _must_ be a comment such as `/** @noinspection PhpMissingBreakStatementInspection */`
when fall-through is intentional in a non-empty `case` body.
* Long if statements _must_ be split onto several lines
when the character/line limit would be exceeded.
** The conditions _must_ be positioned onto the following line, and indented once.
** The logical operators (`&&`, `||`, etc.) _must_ be at the beginning of the line
to make it easier to comment (and exclude) the condition.
** The closing parenthesis and opening brace get their own line at the end of the conditions.
* Control statements should have one space between the control keyword and opening parenthesis,
to distinguish them from function calls.
* Always use curly braces even in situations where they are technically optional.
Having them increases readability and decreases the likelihood of logic errors being introduced
when new lines are added.
* The opening curly should be on the same line as the opening statement,
preceded by one space.
* The closing curly should be on a line by itself and indented to the same level as the opening statement.
* In templates, the alternate control statement syntax using `:` instead of brackets is allowed.
** There _must not_ be a space between the closing parenthesis after the control keyword,
and the colon,
and HTML/PHP inside the control structure should be indented.
* There _must_ be one space after the control structure keyword.
* There _must not_ be a space after the opening parenthesis.
* There _must not_ be a space before the closing parenthesis.
* There _must_ be one space between the closing parenthesis and the opening brace.
* The structure body _must_ be indented once.
* The closing brace _must_ be on the next line after the body.
* The body of each structure _must_ be enclosed by braces.
* Expressions in parentheses _may_ be split across multiple lines,
where each subsequent line is indented at least once.
When doing so, the first expression _must_ be on the next line.
The closing parenthesis and opening brace _must_ be placed together on their own line with one space between them.

== Arrays

* Arrays _must_ be formatted using short array syntax.
* Space separating each element (after the comma) _must_ be used.
* Spaces around the `=>` key association operator, if applicable, _must_ be used.
* Each element _must_ be broken into its own line, and indented one level,
if the line declaring an array spans longer than `120` characters.
* Closing array bracket must be located on a new line,
if the array is broken into multiple lines.
* Comma at the end of the last array element _must_ be used,
if array is broken into multiple lines.

=== Strings

* Single quote strings _should_ be used by default.
* Use double quote string for a deliberate in-line variable interpolation.
** Curly brackets _must_ be used for interpolated variables.
* Use double quote string to avoid escaping single quotes.
* String concatenations _must not_ be used.
** String functions (like `strtr()`) or classes _must_ be used instead.

== Classes and Interfaces

* Separate Interface definition _must_ be provided for each package.
* Classes/Interfaces (and their namespaces) _must_ follow
an link:https://www.php-fig.org/psr/psr-4/[PSR-4: Autoloading Standard].
** File _must_ be named after the class.
** PSR-4 tree _must_ be located in `src` directory.
** Global classes _must not_ be declared.
* Classes/Interfaces _must_ use UpperCamelCase naming.
** Classes/Interfaces _should_ use short names and refer to their namespace for full name context
(e.g.
`link:https://github.com/xtuple/php-util/blob/master/src/Xtuple/Util/HTTP/Request/Request.php[Xtuple\Util\HTTP\Request\Request]`
instead of `Xtuple\Util\HTTP\Request\HTTPRequest`).
** Acronyms in the class/interface names _must_ be in all-uppercase.
** Underscores _must not_ be used.
** Class/Interface names _must not_ have "Class" or "Interface" words in the name.
** Test classes _must_ have the suffix "Test" (as required by PHPUnit).
* Only one class or interface per file _must_ be declared.
** Additional classes and interfaces _may_ be declared in test files,
if used only internally.
* The `extends` and `implements` keywords _must_ be declared on the new line.
* The first implemented interface _must_ be declared on the same line with the `implements` word
** Each following interface _must_ be declared on its own line and indented to the same column as the first interface.
* Class/Interface declarations _must_ have their opening brace on the same line.
* An empty line between start of class/interface definition and property/method definition _must not_ be used.
* An empty line between end of method/property definition and end of class/interface definition _must not_ be used.
* All interfaces should be fully documented according to established documentation standards.
* Parentheses _must_ always be included calling class constructors with no arguments.

=== Namespaces and imports

* There _must_ be only one blank line after the `namespace` declaration.
* There _must_ be only one blank line after the block of `use` declarations.
* `use` declarations _must_ go after the `namespace` declaration.
* There _must_ be only one `use` keyword per declaration.
* Multiple classes _must not_ be specified in a single `use` statement.
* Multiple `use` declarations _must_ be ordered alphabetically ascending.
* Classes/Interfaces with a backslash `\` inside their fully-qualified name
_must not_ use their fully-qualified name inside the code.
* Classes/Interfaces without a backslash `\` inside their fully-qualified name
(e.g. the built-in PHP classes)
_must_ be fully qualified.
* In a file that does not declare a namespace
(and is therefore in the global namespace),
classes in any namespace other than global _must_ be specified with a "use" statement at the top of the file.
* Leading backslash `\` _must not_ be included, when importing a class with "use".
* When specifying a class name in a string, use its full name including namespace,
without leading backslash `\` (consistent with `::class` constant).
* The namespace separator _must_ be in double-quoted strings.
* The namespace separator _must not_ be escaped in single-quoted strings.
* PHP class aliasing _must_ only be done to avoid a name collision.
** If a collision happens, alias both colliding classes by prefixing the next higher portion of the namespace.

=== Constants

* Class/Interface constants _must_ be declared in all-uppercase with underscore separators.
* Visibility _must_ be declared on all constants.
* Constants _must_ be defined using `const` PHP language keyword.
** `define()` _may_ be used when defining a constant conditionally.

=== Properties

* Property names _must_ be declared in lowerCamelCase.
** Acronyms in names _must_ be in all-uppercase.
** Underscores _must not_ be used.
* All properties _must_ be `private`.
** `public` or `protected` accessor ("getter") method _should_ be used to access the property.
* The PHP4-style `var` keyword _must not_ be used to declare a property.
* Only one property _must_ be declared per statement.
* An empty line between end of property definition and start method definition _must_ be used.

=== Methods

* Method names _must_ be declared in lowerCamelCase.
** Acronyms in names _must_ be in all-uppercase.
** Underscores _must not_ be used.
* All methods of classes _must_ specify their visibility: `public`, `protected`, or `private`.
* `abstract` and `final` modifiers _must_ be declared after the visibility.
* `static` modifier _must_ be declared after the visibility and `abstract`/`final`.
* Methods _must_ have PHPDoc, if method signature can not be strictly typed using only PHP
(e.g. `resource` type can not be specified as a type hint).
* If a class has a method that overrides a method from a parent class,
but doesn't call for that parent method,
`/** @noinspection PhpMissingParentCallCommonInspection */` PHPDoc _must_ be used.
** PHPDocs _must_ specify all types.
** Interface _must_ always be used for type hinting,
unless scalar value is used.
* Class _must not_ be used for type hinting.
* Return type declaration present there _must_ be one space after the colon followed by the type declaration.
* The colon and declaration _must_ be on the same line as the argument list closing parentheses
with no spaces between the two characters.
* In nullable type declarations there _must not_ be a space between the question mark and the type.

== Functions

* Functions names _must_ be declared in lowerCamelCase.
* Space _must not_ be used in function call between the function name, the opening parenthesis, and the first parameter.
* Space _must_ be used between commas and each parameter.
* Space _must not_ be used between the last parameter, the closing parenthesis, and the semicolon.
* Parameters in function calls _must_ be split onto several lines. Each parameter _must_ be placed on a new line.
** Parameters need to be indented 2 spaces compared to the level of the function call.
** The opening parenthesis is to be put at the end of the function call line.
** The closing parenthesis gets its own line at the end of the parameters.
* Arguments with default values _must_ be at the end of the argument list.
* Always attempt to return a meaningful value from a function, if one is appropriate.
* Anonymous functions _must_ have a space between "function" and its parameters.
* Space _must_ be used between the closing parenthesis and open curly bracket.
** Curly bracket _must_ be located on the same line.
* Functions with many parameters that exceed characters limit _must_ be split onto several lines.
** The first parameters _must_ be put onto the same line as the function name if there is enough space.
** Subsequent parameters _must_ be on following lines and indented to the match the first parameter.
** The closing parenthesis and the opening brace are to be put onto the same line as the last parameter.

== Variables

* Variables names _must_ be declared in lowerCamelCase.
* Global variables _must not_ be used.

== Closures

* Closures _must_ be declared with a space after the `function` keyword, and a space before and after the `use` keyword.
* The opening brace _must_ go on the same line.
* The closing brace _must_ go on the next line following the body.
* There _must not_ be a space after the opening parenthesis of the argument list or variable list.
* There _must not_ be a space before the closing parenthesis of the argument list or variable list.
* In the argument list and variable list, there _must not_ be a space before each comma.
* In the argument list and variable list, there _must_ be one space after each comma.
* Closure arguments with default values _must_ go at the end of the argument list.
* Argument lists and variable lists _may_ be split across multiple lines, where each subsequent line is indented once.
** The first item in the list _must_ be on the next line.
** There _must_ be only one argument or variable per line.
** The closing parenthesis and opening brace _must_ be placed together on their own line with one space between them.
* Anonymous classes _must_ follow the same guidelines and principles as closures.

== Traits

* The `use` keyword used inside the classes to implement traits
_must_ be declared on the next line after the opening brace.
* Each individual trait that is imported into a class _must_ be included one-per-line
* Each individual trait inclusion _must_ have its own `use` import statement.
* When the class has nothing after the `use` import statement,
the class closing brace _must_ be on the next line after the `use` import statement.
* Otherwise it _must_ have a blank line after the `use` import statement.
* Each `insteadof` and `as` statement usage _must_ be on it own line, indented once.
* `insteadof` and `as` keyword _must_ be have a space before and after.
