= Comments

Comments should be considered a code-smell and a failure to write readable code.
Comments should be used only to explain **why** some irregular code was added
(e.g. to work around some specific problem),
**not what** code is suppose to do.

== PHPDoc

link:https://wiki.php.net/rfc/scalar_type_hints_v5[Scalar type hints] and
link:https://wiki.php.net/rfc/return_types[return types declarations] have been introduced in PHP 7.
This allows remove substantial amount of PHPDocs used previously to declare types to be removed.
PHPDocs should be used for types only to overcome current limitations of PHP
(no `throws` keyword, no generics, etc.)
to provide as strict typing as possible.

* PHPDocs *must not* be used if information can be provided via PHP itself.
* PHPDocs *must* be used for class properties.
* Fully qualified class name *must not* be used.
* PHP core classes *should* be documented as "fully qualified" (e.g. `\Throwable`).
* PHPDocs for overridden and implemented methods *must* be omitted if method signature hasn't changed.
* PHPDocs *should* be used to specify array element types
(*may* be skipped if values are of `mixed` types).
* For nullable type `null` *must* be specified *before* the type
(e.g. `null|string`).
* For a specific boolean value (`true` or `false`) this value *must* be used instead of `bool`
(e.g. `null|false|string`).

Additional PHPDoc tags should be used:

* `@workaround` - to comment code that deals with issues caused by 3rd-party system.
* `@generic` - to tag a method that has generic (`mixed`) parameter(s)
that should be narrowed down in implementations.
* `@override` - to tag a method that has a parent method implementation,
but its call is omitted on purpose.

As often PHPDocs are shown collapsed,
put the overridden/critical information in the first line.

.PHPDoc custom order example
[source]
----
<?php

interface PHPDocs {
  /**
   * @generic //<1>
   *
   * @param int $j
   *
   * @return mixed
   */
  public function element(int $j);
}

final class PHPDocsExample
  implements PHPDocs {
  /**
   * @throws \Throwable //<2>
   *
   * @param int $i
   *
   * @return void
   */
  public function get(int $i): void {}

  /**
   * @return \stdClass //<3>
   * {@inheritdoc}
   */
  public function element() {}
}
----
<1> `@generic` tag marks that `element()` method can be overridden to narrow its type.
<2> `@throws \Throwable` would be visible while PHPDoc is collapsed,
while `@param` and `@return` only duplicate information contained in the method signature.
<3> `@return \stdClass` only overrides generic return type (from `mixed` to `\stdClass`),
so the rest of the PHPDoc can be inherited
